# Generated by Django 4.1.5 on 2023-01-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HamaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagehama', models.ImageField(upload_to='media', verbose_name='imagehama')),
            ],
        ),
    ]
