# Generated by Django 4.1.5 on 2023-01-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0002_hamaimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoshikImgae',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koshikimage', models.ImageField(upload_to='media', verbose_name='Koshik Image')),
            ],
        ),
        migrations.AlterField(
            model_name='hamaimage',
            name='imagehama',
            field=models.ImageField(upload_to='media', verbose_name='Hamazgest Image'),
        ),
    ]
