# Generated by Django 4.1.5 on 2023-01-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0003_koshikimgae_alter_hamaimage_imagehama'),
    ]

    operations = [
        migrations.CreateModel(
            name='AqsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aqsimage', models.ImageField(upload_to='media', verbose_name='Aqs Image')),
            ],
        ),
        migrations.CreateModel(
            name='ZenqerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zenqerimage', models.ImageField(upload_to='media', verbose_name='Zenqer Image')),
            ],
        ),
    ]
